{
 "title": "AccessPoint",
 "tags": [ "Omada" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "increase_interval", "query": "${VAR_INCREASE_INTERVAL}" }
  ]
 },
 "panels": [
  {
   "title": "Transferred",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(radio_rx_sum[$__range]) + increase(radio_tx_sum[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bandwidth",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(radio_rx_sum[$increase_interval]) + increase(radio_tx_sum[$increase_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Channels utilization",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(radio_rx_util) by (frequency) + avg(radio_tx_util) by (frequency)",
     "legendFormat": "{{frequency}}"
    }
   ]
  },
  {
   "title": "Wireless Config",
   "type": "table",
   "gridPos": { "h": 10, "w": 14, "x": 10, "y": 5 },
   "targets": [
    { "expr": "radio_info", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "5 GHz Rate",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(radio_rx_sum{frequency=\"5 GHz\"}[$increase_interval]) + increase(radio_tx_sum{frequency=\"5 GHz\"}[$increase_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "2.4 GHz Rate",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(radio_rx_sum{frequency=\"2.4 GHz\"}[$increase_interval]) + increase(radio_tx_sum{frequency=\"2.4 GHz\"}[$increase_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "increase(radio_rx_sum[$increase_interval]) + increase(radio_tx_sum[$increase_interval])",
     "legendFormat": "{{name}}-{{frequency}}"
    }
   ]
  },
  {
   "title": "Retries",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "increase(radio_tx_pkts_retry_sum[$increase_interval]) +  increase(radio_rx_pkts_retry_sum[$increase_interval])",
     "legendFormat": "{{name}}-{{frequency}}"
    }
   ]
  },
  {
   "title": "Resource consumption",
   "type": "timeseries",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    {
     "expr": "cpu_usage{deviceType=\"AccessPoint\"}",
     "legendFormat": "{{name}} ({{__name__}})"
    },
    {
     "expr": "memory_usage{deviceType=\"AccessPoint\"}",
     "legendFormat": "{{name}} ({{__name__}})"
    }
   ]
  },
  {
   "title": "Devices",
   "type": "table",
   "gridPos": { "h": 10, "w": 18, "x": 0, "y": 61 },
   "targets": [
    {
     "expr": "device_info{deviceType=\"AccessPoint\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}