{
 "title": "Switch",
 "tags": [ "Omada" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "increase_interval", "query": "${VAR_INCREASE_INTERVAL}" }
  ]
 },
 "panels": [
  {
   "title": "Transferred",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(switch_port_tx_sum[$__range]) + increase(switch_port_rx_sum[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bandwidth",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(switch_port_tx_sum[$increase_interval]) + increase(switch_port_rx_sum[$increase_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Port 1",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "switch_port_info{port=\"1\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Port 3",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "switch_port_info{port=\"3\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Port 5",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "switch_port_info{port=\"5\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Port 7",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "switch_port_info{port=\"7\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Port 9",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "switch_port_info{port=\"9\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Port 11",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "switch_port_info{port=\"11\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Port 13",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "switch_port_info{port=\"13\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Port 15",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "switch_port_info{port=\"15\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Port 17",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "switch_port_info{port=\"17\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Port Usage",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(count(switch_port_info{linkSpeed!=\"Down\"})/count(switch_port_info)) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Port 2",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "switch_port_info{port=\"2\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Port 4",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "switch_port_info{port=\"4\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Port 6",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "switch_port_info{port=\"6\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Port 8",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "switch_port_info{port=\"8\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Port 10",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "switch_port_info{port=\"10\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Port 12",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "switch_port_info{port=\"12\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Port 14",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "switch_port_info{port=\"14\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Port 16",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "switch_port_info{port=\"16\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Port 18",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "switch_port_info{port=\"18\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Rate port 1",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  (increase(switch_port_tx_sum{port=\"1\"}[$increase_interval]) + increase(switch_port_rx_sum{port=\"1\"}[$increase_interval]))\n  * on (port) group_left()\n  (switch_port_info{port=\"1\", linkSpeed!=\"Down\"} == 1)\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate port 3",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  (increase(switch_port_tx_sum{port=\"3\"}[$increase_interval]) + increase(switch_port_rx_sum{port=\"3\"}[$increase_interval]))\n  * on (port) group_left()\n  (switch_port_info{port=\"3\", linkSpeed!=\"Down\"} == 1)\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate port 5",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  (increase(switch_port_tx_sum{port=\"5\"}[$increase_interval]) + increase(switch_port_rx_sum{port=\"5\"}[$increase_interval]))\n  * on (port) group_left()\n  (switch_port_info{port=\"5\", linkSpeed!=\"Down\"} == 1)\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate port 7",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  (increase(switch_port_tx_sum{port=\"7\"}[$increase_interval]) + increase(switch_port_rx_sum{port=\"7\"}[$increase_interval]))\n  * on (port) group_left()\n  (switch_port_info{port=\"7\", linkSpeed!=\"Down\"} == 1)\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate port 9",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  (increase(switch_port_tx_sum{port=\"9\"}[$increase_interval]) + increase(switch_port_rx_sum{port=\"9\"}[$increase_interval]))\n  * on (port) group_left()\n  (switch_port_info{port=\"9\", linkSpeed!=\"Down\"} == 1)\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate port 11",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  (increase(switch_port_tx_sum{port=\"11\"}[$increase_interval]) + increase(switch_port_rx_sum{port=\"11\"}[$increase_interval]))\n  * on (port) group_left()\n  (switch_port_info{port=\"11\", linkSpeed!=\"Down\"} == 1)\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate port 13",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  (increase(switch_port_tx_sum{port=\"13\"}[$increase_interval]) + increase(switch_port_rx_sum{port=\"13\"}[$increase_interval]))\n  * on (port) group_left()\n  (switch_port_info{port=\"13\", linkSpeed!=\"Down\"} == 1)\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate port 15",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  (increase(switch_port_tx_sum{port=\"15\"}[$increase_interval]) + increase(switch_port_rx_sum{port=\"15\"}[$increase_interval]))\n  * on (port) group_left()\n  (switch_port_info{port=\"15\", linkSpeed!=\"Down\"} == 1)\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate port 2",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  (increase(switch_port_tx_sum{port=\"2\"}[$increase_interval]) + increase(switch_port_rx_sum{port=\"2\"}[$increase_interval]))\n  * on (port) group_left()\n  (switch_port_info{port=\"2\", linkSpeed!=\"Down\"} == 1)\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate port 4",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  (increase(switch_port_tx_sum{port=\"4\"}[$increase_interval]) + increase(switch_port_rx_sum{port=\"4\"}[$increase_interval]))\n  * on (port) group_left()\n  (switch_port_info{port=\"4\", linkSpeed!=\"Down\"} == 1)\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate port 6",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  (increase(switch_port_tx_sum{port=\"6\"}[$increase_interval]) + increase(switch_port_rx_sum{port=\"6\"}[$increase_interval]))\n  * on (port) group_left()\n  (switch_port_info{port=\"6\", linkSpeed!=\"Down\"} == 1)\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate port 8",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  (increase(switch_port_tx_sum{port=\"8\"}[$increase_interval]) + increase(switch_port_rx_sum{port=\"8\"}[$increase_interval]))\n  * on (port) group_left()\n  (switch_port_info{port=\"8\", linkSpeed!=\"Down\"} == 1)\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate port 10",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  (increase(switch_port_tx_sum{port=\"10\"}[$increase_interval]) + increase(switch_port_rx_sum{port=\"10\"}[$increase_interval]))\n  * on (port) group_left()\n  (switch_port_info{port=\"10\", linkSpeed!=\"Down\"} == 1)\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate port 12",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  (increase(switch_port_tx_sum{port=\"12\"}[$increase_interval]) + increase(switch_port_rx_sum{port=\"12\"}[$increase_interval]))\n  * on (port) group_left()\n  (switch_port_info{port=\"12\", linkSpeed!=\"Down\"} == 1)\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate port 14",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  (increase(switch_port_tx_sum{port=\"14\"}[$increase_interval]) + increase(switch_port_rx_sum{port=\"14\"}[$increase_interval]))\n  * on (port) group_left()\n  (switch_port_info{port=\"14\", linkSpeed!=\"Down\"} == 1)\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate port 16",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  (increase(switch_port_tx_sum{port=\"16\"}[$increase_interval]) + increase(switch_port_rx_sum{port=\"16\"}[$increase_interval]))\n  * on (port) group_left()\n  (switch_port_info{port=\"16\", linkSpeed!=\"Down\"} == 1)\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate port 17 SFP",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  (increase(switch_port_tx_sum{port=\"17\"}[$increase_interval]) + increase(switch_port_rx_sum{port=\"17\"}[$increase_interval]))\n  * on (port) group_left()\n  (switch_port_info{port=\"17\", linkSpeed!=\"Down\"} == 1)\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate port 18 SFP",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  (increase(switch_port_tx_sum{port=\"18\"}[$increase_interval]) + increase(switch_port_rx_sum{port=\"18\"}[$increase_interval]))\n  * on (port) group_left()\n  (switch_port_info{port=\"18\", linkSpeed!=\"Down\"} == 1)\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Resource consumption",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    {
     "expr": "cpu_usage{deviceType=\"Switch\"}",
     "legendFormat": "{{name}} ({{__name__}})"
    },
    {
     "expr": "memory_usage{deviceType=\"Switch\"}",
     "legendFormat": "{{name}} ({{__name__}})"
    }
   ]
  },
  {
   "title": "Devices",
   "type": "table",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "device_info{deviceType=\"Switch\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}